# Uncomment if needed:
#proxy: http://proxy.url
api:
  - method: GET
    url: /fake-example
    fixture: fixture.example.json
  - method: POST
    url: /fake-example
    fixture: fixture.example.json
  - method: HEAD
    url: /fake-example
    fixture: fixture.example.json